name: create-release
description: Creates releases using tags and git logs.

inputs:
    tag-name:
        description: Tag name which will be used as release name
        required: true

runs:
    using: composite
    steps:
        - uses: actions/checkout@v3